/**
 * Palette — Single source of truth for colour values
 *
 * Used by:
 * - opengraph-image.tsx (server-side, can't read CSS vars)
 * - Any server component needing colour values
 *
 * Generated by: scripts/generate-palette.mjs
 * CSS tokens in: src/styles/colour-tokens.css (keep in sync)
 */

export const palette = {
  primary: { oklch: "oklch(60% 0.20 5)", hex: "#da3870" },
  primaryLight: { oklch: "oklch(75% 0.20 5)", hex: "#ff6d9d" },
  primaryMuted: { oklch: "oklch(50% 0.10 5)", hex: "#92495b" },
  accent: { oklch: "oklch(78% 0.16 85)", hex: "#e6ad00" },
  accentMuted: { oklch: "oklch(58% 0.10 85)", hex: "#94752f" },
  surface1: { oklch: "oklch(12% 0.01 260)", hex: "#040609" },
  surface2: { oklch: "oklch(16% 0.01 260)", hex: "#090d14" },
  surface3: { oklch: "oklch(24% 0.02 260)", hex: "#1a2029" },
  surface4: { oklch: "oklch(30% 0.03 260)", hex: "#272e3b" },
  textPrimary: { oklch: "oklch(95% 0.005 5)", hex: "#f2edee" },
  textSecondary: { oklch: "oklch(75% 0.02 5)", hex: "#baa9ac" },
  textMuted: { oklch: "oklch(55% 0.02 260)", hex: "#6b727e" },
} as const;

/** OG image gradients — hex/rgba for Satori compatibility */
export const ogGradients = {
  background: "linear-gradient(150deg, #040609 0%, #090d14 50%, #1a2029 100%)",
  glow: "radial-gradient(circle, rgba(218,56,112,0.2) 0%, transparent 60%)",
  accentText: "rgba(230,173,0,0.9)",
  gridLine: "rgba(218,56,112,0.08)",
} as const;

export type PaletteToken = keyof typeof palette;