/**
 * Palette — Single source of truth for colour values
 *
 * Used by:
 * - opengraph-image.tsx (server-side, can't read CSS vars)
 * - Any server component needing colour values
 *
 * Generated by: scripts/generate-palette.mjs
 * CSS tokens in: src/styles/colour-tokens.css (keep in sync)
 *
 * Usage:
 *   node scripts/generate-palette.mjs --family <family> --primary-hue <hue> --mood <mood> --name <name> --output-dir src/
 *   Then move palette.ts to src/lib/palette.ts
 *
 * IMPORTANT: Do NOT edit manually — regenerate with the script to keep
 * CSS tokens, DaisyUI theme, and this file in sync.
 */

export const palette = {
  primary:       { oklch: "oklch(60% 0.20 240)", hex: "#REPLACE" },
  primaryLight:  { oklch: "oklch(75% 0.20 240)", hex: "#REPLACE" },
  primaryMuted:  { oklch: "oklch(50% 0.10 240)", hex: "#REPLACE" },
  accent:        { oklch: "oklch(78% 0.16 175)", hex: "#REPLACE" },
  accentMuted:   { oklch: "oklch(58% 0.10 175)", hex: "#REPLACE" },
  surface1:      { oklch: "oklch(12% 0.01 250)", hex: "#REPLACE" },
  surface2:      { oklch: "oklch(16% 0.01 250)", hex: "#REPLACE" },
  surface3:      { oklch: "oklch(24% 0.02 250)", hex: "#REPLACE" },
  surface4:      { oklch: "oklch(30% 0.03 250)", hex: "#REPLACE" },
  textPrimary:   { oklch: "oklch(95% 0.005 240)", hex: "#REPLACE" },
  textSecondary: { oklch: "oklch(75% 0.02 240)", hex: "#REPLACE" },
  textMuted:     { oklch: "oklch(55% 0.02 240)", hex: "#REPLACE" },
} as const;

/** OG image gradients — hex/rgba for Satori compatibility */
export const ogGradients = {
  background: "linear-gradient(150deg, #REPLACE 0%, #REPLACE 50%, #REPLACE 100%)",
  glow: "radial-gradient(circle, rgba(0,0,0,0.2) 0%, transparent 60%)",
  accentText: "rgba(0,0,0,0.9)",
  gridLine: "rgba(0,0,0,0.08)",
} as const;

export type PaletteToken = keyof typeof palette;
